import os
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field


MODEL_PATH = Path(os.getenv("MODEL_PATH", Path(__file__).parents[1] / "model" / "loan_model.joblib"))

if not MODEL_PATH.exists():
    raise RuntimeError(f"Model file not found: {MODEL_PATH}")

bundle = joblib.load(MODEL_PATH)
model = bundle["model"]
features = bundle["features"]

app = FastAPI(
    title="Loan Assessment API",
    description="Loads the model generated by the Day 5 deployment notebook.",
    version=bundle["version"],
)


class Applicant(BaseModel):
    income: int = Field(ge=15_000, le=120_000)
    age: int = Field(ge=21, le=65)
    loan_amount: int = Field(ge=5_000, le=80_000)
    credit_score: int = Field(ge=300, le=850)
    existing_debt: int = Field(ge=0, le=50_000)


@app.get("/health")
def health():
    return {
        "status": "ok",
        "model_version": bundle["version"],
        "test_accuracy": bundle["metrics"]["accuracy"],
    }


@app.post("/predict")
def predict(applicant: Applicant):
    frame = pd.DataFrame([applicant.model_dump()])[features]
    approval_probability = float(model.predict_proba(frame)[0, 1])
    approved = approval_probability >= 0.5

    scaler = model.named_steps["scaler"]
    classifier = model.named_steps["classifier"]
    scaled_values = scaler.transform(frame)[0]
    contributions = scaled_values * classifier.coef_[0]

    if not np.isfinite(contributions).all():
        raise HTTPException(status_code=500, detail="Model explanation could not be calculated")

    return {
        "decision": "Approved" if approved else "Declined",
        "approved": approved,
        "confidence": round(max(approval_probability, 1 - approval_probability) * 100, 1),
        "approval_probability": round(approval_probability, 4),
        "explanation": {
            feature: round(float(value), 3)
            for feature, value in zip(features, contributions)
        },
        "model_version": bundle["version"],
    }
